version: '3.6'

services:
  app:
    build:
      context: .
      target: base
      args:
        NODE_ENV: development
    command: yarn start
    ports:
      - 8080:8080
    volumes:
      - ${PWD-.}:/usr/app
